//
//  StatesForTesting.swift
//  Race for the White House
//
//  Created by Scott Caruso on 2/15/16.
//  Copyright © 2016 Scott Caruso. All rights reserved.
//

import Foundation

let democrats = PoliticalParty(thisParty: "Democrat", thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue())

let republicans = PoliticalParty(thisParty: "Republican", thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue())

let parties = [(party:democrats,percentage:randomPartyIDValue()),(party:republicans,percentage:randomPartyIDValue())]

let alabama = State(thisState: "Alabama", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 9, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let alaska = State(thisState: "Alaska", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let arizona = State(thisState: "Arizona", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 11, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let arkansas = State(thisState: "Arkansas", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 6, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let california = State(thisState: "California", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 55, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let colorado = State(thisState: "Colorado", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 9, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let connecticut = State(thisState: "Connecticut", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 7, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let delaware = State(thisState: "Delaware", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let florida = State(thisState: "Florida", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 29, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let georgia = State(thisState: "Georgia", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 16, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let hawaii = State(thisState: "Hawaii", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 4, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let idaho = State(thisState: "Idaho", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 4, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let illinois = State(thisState: "Illinois", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 20, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let indiana = State(thisState: "Indiana", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 11, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let iowa = State(thisState: "Iowa", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 6, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let kansas = State(thisState: "Kansas", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 6, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let kentucky = State(thisState: "Kentucky", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 8, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let louisiana = State(thisState: "Louisiana", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 8, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let maine = State(thisState: "Maine", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 4, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let maryland = State(thisState: "Maryland", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 10, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let massachusetts = State(thisState: "Massachusetts", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 11, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let michigan = State(thisState: "Michigan", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 16, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let minnesota = State(thisState: "Minnesota", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 10, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let mississippi = State(thisState: "Mississippi", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 6, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let missouri = State(thisState: "Missouri", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 10, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let montana = State(thisState: "Montana", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let nebraska = State(thisState: "Nebraska", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 5, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let nevada = State(thisState: "Nevada", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 6, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let newHampshire = State(thisState: "New Hampshire", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 4, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let newJersey = State(thisState: "New Jersey", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 14, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let newMexico = State(thisState: "New Mexico", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 5, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let newYork = State(thisState: "New York", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 29, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let northCarolina = State(thisState: "North Carolina", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 15, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let northDakota = State(thisState: "North Dakota", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let ohio = State(thisState: "Ohio", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 18, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let oklahoma = State(thisState: "Oklahoma", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 7, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let oregon = State(thisState: "Oregon", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 7, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let pennsylvania = State(thisState: "Pennsylvania", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 20, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let rhodeIsland = State(thisState: "Rhode Island", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 4, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let southCarolina = State(thisState: "South Carolina", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 9, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let southDakota = State(thisState: "South Dakota", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let tennessee = State(thisState: "Tennessee", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 11, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let texas = State(thisState: "Texas", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 38, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let utah = State(thisState: "Utah", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 6, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let vermont = State(thisState: "Vermont", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let virginia = State(thisState: "Virginia", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 13, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let washington = State(thisState: "Washington", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 12, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let westVirginia = State(thisState: "West Virginia", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 5, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let wisconsin = State(thisState: "Wisconsin", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 10, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let wyoming = State(thisState: "Wyoming", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let dc = State(thisState: "Washington, D.C.", thisPopulation: 10000000, thisPercent: 0.42, thisElectoralVotes: 3, thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), parties:parties)

let states = [alabama,alaska,arizona,arkansas,california,colorado,connecticut,delaware,florida,georgia,hawaii,idaho,illinois,indiana,iowa,kansas,kentucky,louisiana,maine,maryland,massachusetts,michigan,minnesota,mississippi,missouri,montana,nebraska,nevada,newHampshire,newJersey,newMexico,newYork,northCarolina,northDakota,ohio,oklahoma,oregon,pennsylvania,rhodeIsland,southCarolina,southDakota,tennessee,texas,utah,vermont,virginia,washington,westVirginia,wisconsin,wyoming,dc]

let candidateOne = Candidate(thisName: "Hillary Clinton", thisExperience: 25, thisCharisma: 25, thisAttractiveness: 25, thisAuthenticity: 25, thisNoteriety: 25, thisIntelligence: 25, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), thisParty: democrats)

let candidateTwo = Candidate(thisName: "Donald Trump", thisExperience: 0, thisCharisma: 50, thisAttractiveness: 15, thisAuthenticity: 30, thisNoteriety: 50, thisIntelligence: 30, thisHealthcare: randomNegativeValue() , thisGayMarriage: randomNegativeValue() , thisHomelandSecurity: randomNegativeValue() , thisImmigration: randomNegativeValue() , thisTaxCode: randomNegativeValue(), thisBusinessTaxes: randomNegativeValue(), thisOutsourcing: randomNegativeValue() , thisCleanEnergy: randomNegativeValue() , thisLegalPot: randomNegativeValue() , thisCriminalJustice: randomNegativeValue() , thisChildrensEducation: randomNegativeValue(), thisPostSecondary: randomNegativeValue() , thisFracking: randomNegativeValue(), thisSocialSecurity: randomNegativeValue(), thisMedicareMedicaid: randomNegativeValue(), thisGovernmentSpending: randomNegativeValue(), thisGunControl: randomNegativeValue(), thisClimateChange: randomNegativeValue(), thisParty: republicans)

func randomNegativeValue() -> Double {
  var value = (Double(arc4random())/Double(UINT32_MAX))*50
  let negativeRandomizer = Int(arc4random_uniform(2))
  if negativeRandomizer == 0 {
    value = 0 - value
  }
  return value
}

func randomPartyIDValue() -> Double {
  let value = (Double(arc4random_uniform(11))+29)
  let decimalValue = (Double(arc4random())/Double(UINT32_MAX))
  let totalValue = value+decimalValue
  return totalValue
}
